#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  8 10:39:23 2021

@author: rancy
"""

# =============================================================================
# # Python with MongoDB
# =============================================================================

#Python is a backend technology and it can be connected with different data base applications such as MongoDB and SQL.

## MongoDB

#MongoDB is a NoSQL database. MongoDB stores data in a JSON like document which make MongoDB very flexible and scalable. Let's see the different terminologies of SQL and NoSQL databases. The following table will make the difference between SQL vs NoSQL databases.

### SQL versus NoSQL

### Getting Connection String(MongoDB URI)

#Copy the connection string only link and you get something like this

'''
mongodb+srv://Rancy:<password>@cluster0.niwbb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
'''

#Python needs a mongoDB driver to access mongoDB database. We will use _pymongo_ with _dnspython_ to connect our application with mongoDB base . Inside your project directory install pymongo and dnspython.
'''
pip install pymongo dnspython
'''

### Connecting Flask application to MongoDB Cluster

'''
# let's import the flask
from flask import Flask, render_template
import os # importing operating system module
MONGODB_URI = 'mongodb+srv://Rancy:<password>@cluster0.niwbb.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
client = pymongo.MongoClient(MONGODB_URI)
print(client.list_database_names())

app = Flask(__name__)
if __name__ == '__main__':
    # for deployment we use the environ
    # to make it work for both production and development
    port = int(os.environ.get("PORT", 5000))
    app.run(debug=True, host='0.0.0.0', port=port)
'''

# When we run the above code we get the default mongoDB databases.

### Creating a database and collection

#Let's create a database, database and collection in mongoDB will be created if it doesn't exist. Let's create a data base name _thirty_days_of_python_ and _students_ collection.
## To create a database
'''
db = client.name_of_databse # we can create a database like this or the second way
db = client['name_of_database']
'''

    
