#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  7 08:29:37 2021

@author: rancy
"""

# =============================================================================
# ## Python *datetime*

# ## Python has got _datetime_ module to handle date and time.

# =============================================================================

import datetime

print(dir(datetime))

#With dir or help built-in commands it is possible to know the available functions in a certain module. As you can see, in the datetime module there are many functions, but we will focus on _date_, _datetime_, _time_ and _timedelta_. Let's see them one by one.

### Getting *datetime* Information

from datetime import datetime

now = datetime.now()
print(now)                     
day = now.day                 
month = now.month               
year = now.year                
hour = now.hour                
minute = now.minute             
second = now.second
timestamp = now.timestamp()
print(day, month, year, hour, minute)
print('timestamp', timestamp)
print(f'{day}/{month}/{year}, {hour}:{minute}')  

# Timestamp or Unix timestamp is the number of seconds elapsed from 1st of January 1970 UTC.

### Formating Date Output Using *strftime*

from datetime import datetime

new_year = datetime(2022, 1, 1)
print(new_year)      
day = new_year.day
month = new_year.month
year = new_year.year
hour = new_year.hour
minute = new_year.minute
second = new_year.second
print(day, month, year, hour, minute) 
print(f'{day}/{month}/{year}, {hour}:{minute}') 

#Time formating
from datetime import datetime

# current date and time
now = datetime.now()
t = now.strftime("%H:%M:%S")
print("time:", t)
time_one = now.strftime("%m/%d/%Y, %H:%M:%S")
# mm/dd/YY H:M:S format
print("time one:", time_one)
time_two = now.strftime("%d/%m/%Y, %H:%M:%S")
# dd/mm/YY H:M:S format
print("time two:", time_two)


### String to Time Using *strptime*

from datetime import datetime

date_string = "7 March, 2021"
print("date_string =", date_string)
date_object = datetime.strptime(date_string, "%d %B, %Y")
print("date_object =", date_object)

### Using *date* from *datetime*

from datetime import date

d = date(2022, 1, 1)
print(d)
print('Current date:', d.today())    
# date object of today's date
today = date.today()
print("Current year:", today.year)   
print("Current month:", today.month) 
print("Current day:", today.day)  


### Time Objects to Represent Time

from datetime import time

# time(hour = 0, minute = 0, second = 0)
a = time()
print("a =", a)
# time(hour, minute and second)
b = time(8, 53, 36)
print("b =", b)
# time(hour, minute and second)
c = time(hour=8, minute=53, second=36)
print("c =", c)
# time(hour, minute, second, microsecond)
d = time(8, 53, 36, 200555)
print("d =", d)   


### Difference Between Two Points in Time

today = date(year=2021, month=3, day=7)
new_year = date(year=2022, month=1, day=1)
time_left_for_newyear = new_year - today
# Time left for new year:  27 days, 0:00:00
print('Time left for new year: ', time_left_for_newyear)

t1 = datetime(year = 2021, month = 3, day = 7, hour = 0, minute = 59, second = 0)
t2 = datetime(year = 2022, month = 1, day = 1, hour = 0, minute = 0, second = 0)
diff = t2 - t1
print('Time left for new year:', diff) 

### Difference Between Two Points in Time Using *timedelata*

from datetime import timedelta

t1 = timedelta(weeks=12, days=10, hours=4, seconds=20)
t2 = timedelta(days=7, hours=5, minutes=3, seconds=30)
t3 = t1 - t2
print("t3 =", t3)


## 💻 Exercises: Day 16

#1. Get the current day, month, year, hour, minute and timestamp from datetime module
from datetime import datetime

now = datetime.now()
print(now)                     
day = now.day                 
month = now.month               
year = now.year                
hour = now.hour                
minute = now.minute             
second = now.second
timestamp = now.timestamp()
print(day, month, year, hour, minute)
print('timestamp', timestamp)
print(f'{day}/{month}/{year}, {hour}:{minute}')  
#2. Format the current date using this format: "%m/%d/%Y, %H:%M:%S")
now = datetime.now()
t = now.strftime("%H:%M:%S")
print("time:", t)
time_one = now.strftime("%m/%d/%Y, %H:%M:%S")
#3. Today is 5 December, 2019. Change this time string to time.
date_string = " 5 December, 2019"
print("date_string =", date_string)
date_object = datetime.strptime(date_string, "%d %B, %Y")
print("date_object =", date_object)
#4. Calculate the time difference between now and new year.
t1 = datetime(year = 2021, month = 3, day = 7, hour = 0, minute = 59, second = 0)
t2 = datetime(year = 2022, month = 1, day = 1, hour = 0, minute = 0, second = 0)
diff = t2 - t1
print('Time left for new year:', diff) 
#5. Calculate the time difference between 1 January 1970 and now.
timestamp = now.timestamp()
print(day, month, year, hour, minute)
print('timestamp', timestamp)
#6. Think, what can you use the datetime module for? Examples:
#   - Time series analysis
#   - To get a timestamp of any activities in an application
#   - Adding posts on a blog 